[package]
name = "devices-port"
version = "0.1.0"
edition = "2024"

[dependencies]
ip-api-adapter.workspace = true
async-trait.workspace = true
tokio.workspace = true
devices-adapter.workspace = true
entities.workspace = true
