[package]
name = "agent_connection"
version = "0.1.0"
edition = "2024"

[dependencies]
common.workspace = true
ports.workspace = true
entities.workspace = true

uuid.workspace = true
dashmap.workspace = true
tokio.workspace = true
async-trait.workspace = true
