[package]
name = "entities"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono.workspace = true
strum.workspace = true
serde.workspace = true
serde_with.workspace = true
uuid.workspace = true
tokio.workspace = true
